from __future__ import annotations
import os
from structure import IRGraph, IRActor, OpType, OPTYPE_TO_LOOP_FN, OPTYPE_TO_PI
from actor_codegen import get_codegen
from pi_generator import SKIP_OPS


# Path to sources/generated/ — relative to the scripts/ working directory.
GENERATED_DIR = "../sources/generated"

RUNTIME_INCLUDES = """\
#include <map>
#include <vector>
#include <cstring>
#include <cmath>
#include "runtime/dnnl_utils.h"
#include "runtime/blas_utils.h"
"""


def _extract_int_params(actor: IRActor) -> dict:
    """
    {param_name: int_value} from an actor's attached IRParams.
    Non-integer params (e.g. epsilon stored as "1en05") are silently skipped;
    their codegens read them directly from actor.attributes instead.
    """
    params = {}
    for _, param in actor.params:
        try:
            params[param.name] = int(param.value)
        except ValueError:
            pass
    return params


def generate_model_actors(graph: IRGraph, isHierarchial, model_name: str) -> dict[str, str]:
    """
    Generate one C++ function per unique operator type in the graph.

    Returns
    -------
    loop_fn_map : dict[actor.unique_name -> loop_fn_name]
        For generated actors: the base function name (e.g. "conv2d_bias").
        For non-generated actors: fallback from OPTYPE_TO_LOOP_FN.
    """
    os.makedirs(GENERATED_DIR, exist_ok=True)
    h_path   = os.path.join(GENERATED_DIR, f"{model_name}_actors.h")
    cpp_path = os.path.join(GENERATED_DIR, f"{model_name}_actors.cpp")

    declarations = []
    definitions  = []
    loop_fn_map  = {}
    seen_op_types: set[OpType] = set()

    for actor in graph.actors:
        codegen = get_codegen(actor.op_type)

        if codegen is None:
            # No generated kernel — keep the handwritten header/function.
            loop_fn_map[actor.unique_name] = OPTYPE_TO_LOOP_FN.get(actor.op_type, "")
            continue

        fn_name = codegen.loop_fn(actor)  # e.g. "conv2d_bias"
        loop_fn_map[actor.unique_name] = fn_name

        # An op is parallelized when hierarchical AND it gets a .pi subgraph
        is_parallel = (isHierarchial
                        and actor.op_type in OPTYPE_TO_PI
                        and actor.op_type not in SKIP_OPS)
        # Point the actor's graph_desc at the generated header so PREESM
        # finds the function declaration during code generation.
        if not is_parallel :
            actor.source = f"/Code/include/runtime/{model_name}_actors.h" 

        # Generate the function body only once per operator type.
        if actor.op_type not in seen_op_types:
            seen_op_types.add(actor.op_type)
            params = _extract_int_params(actor)
            declarations.append(codegen.decl(actor, params))
            definitions.append(codegen.defn(actor, params, parallel=is_parallel))

            # Emit the keep-aware block-skip variant (residual ADD types only).
            # block_skipping_pass.py repoints residual ADD actors at this
            # `<base>_skip` function in dy_resnet_blockdrop.pi.
            skip_definition = codegen.skip_defn(actor, params)
            if skip_definition is not None:
                declarations.append(codegen.skip_decl(actor, params))
                definitions.append(skip_definition)

    # -----------------------------------------------------------------
    # Write header
    # -----------------------------------------------------------------
    with open(h_path, "w") as f:
        f.write("// Auto-generated by model_codegen.py — do not edit\n")
        f.write("#pragma once\n\n")
        f.write("\n".join(declarations))
        f.write("\n")

    # -----------------------------------------------------------------
    # Write implementation
    # -----------------------------------------------------------------
    with open(cpp_path, "w") as f:
        f.write("// Auto-generated by model_codegen.py — do not edit\n")
        f.write(RUNTIME_INCLUDES)
        f.write(f'#include "{model_name}_actors.h"\n')
        f.write("\n")
        f.write("\n\n".join(definitions))
        f.write("\n")

    print(f"  Generated {h_path}")
    print(f"  Generated {cpp_path}")
    return loop_fn_map


def generate_weight_loader_actors(graph: IRGraph, model_name: str) -> None:
    """
    emit the fused load+split weight kernels for the dynamic
    block-drop graph.

    Runs *after* `block_skipping_pass.apply_block_skipping_pass`, which fuses
    each gated ``LOAD_WEIGHTS + SPLIT_WEIGHTS`` pair into a single ``loadsplit``
    actor carrying the per-weight file layout (`_weight_layout`) and which
    outputs are gated (`_gated_outputs`).  For each such actor we emit one
    self-contained function that reads every weight straight from the weights
    file (inline ``fseek``/``fread`` — no dependency on the project's
    ``loadWeights``) at its absolute byte offset, skipping dropped blocks:

        void load_split_weights_float(int sizeWeights, int keep_0, ...,
                                      float* out_0, float* out_1, ...) {
            std::FILE* f = std::fopen("weights.bin", "rb");
            if (!f) { ...; return; }
            std::fseek(f, OFF0, SEEK_SET); std::fread(out_0, 1, SZ0, f);            // ungated
            if (keep_0) { std::fseek(f, OFF1, SEEK_SET); std::fread(out_1, 1, SZ1, f); }
            ...
            std::fclose(f);
        }

    The file is opened once per firing (cheaper than the old per-weight
    open/close).  Bodies are appended to the already-generated actor files; each
    actor's `.source` is repointed at the generated header.  No-op when there
    are no fused actors (e.g. a model with no residual blocks).
    """
    fused = [a for a in graph.actors if a.attributes.get("_kind") == "loadsplit"]
    if not fused:
        return

    h_path   = os.path.join(GENERATED_DIR, f"{model_name}_actors.h")
    cpp_path = os.path.join(GENERATED_DIR, f"{model_name}_actors.cpp")
    header   = f"/Code/include/runtime/{model_name}_actors.h"

    decls, defns = [], []
    for actor in fused:
        fn      = actor.attributes["_loop_fn"]
        layout  = actor.attributes.get("_weight_layout", {})
        gated   = actor.attributes.get("_gated_outputs", {})

        sig_parts = [f"int {p.name}" for p, _ in actor.params]
        for port, tensor in actor.outputs:
            sig_parts.append(f"{tensor.dtype}* {port.name}")
        sig = ", ".join(sig_parts)

        body = [
            '    std::FILE* f = std::fopen("weights.bin", "rb");',
            f'    if (!f) {{ std::fprintf(stderr, "[{fn}] cannot open weights.bin\\n"); return; }}',
        ]
        for port, _ in actor.outputs:
            info = layout.get(port.name)
            if info is None:
                continue   # output with no recorded layout — skip defensively
            read = (f"std::fseek(f, {info['offset']}, SEEK_SET); "
                    f"std::fread({port.name}, 1, {info['size']}, f);")
            uid  = gated.get(port.name)
            body.append(f"    if ({uid}) {{ {read} }}" if uid else f"    {read}")
        body.append("    std::fclose(f);")

        decls.append(f"void {fn}({sig});")
        defns.append(f"void {fn}({sig})\n{{\n" + "\n".join(body) + "\n}")
        actor.source = header

    with open(h_path, "a") as f:
        f.write("\n// --- Fused load+split weight loaders (dynamic block-drop) ---\n")
        f.write("\n".join(decls))
        f.write("\n")

    with open(cpp_path, "a") as f:
        f.write("\n// --- Fused load+split weight loaders (dynamic block-drop) ---\n")
        f.write("#include <cstdio>\n\n")
        f.write("\n\n".join(defns))
        f.write("\n")

    print(f"  Appended {len(fused)} fused load+split kernel(s) to {h_path} / {cpp_path}")
