from __future__ import annotations
import os
from structure import IRGraph, IRActor, OpType, OPTYPE_TO_LOOP_FN, OPTYPE_TO_PI
from actor_codegen import get_codegen
from pi_generator import SKIP_OPS


# Path to sources/generated/ — relative to the scripts/ working directory.
GENERATED_DIR = "../sources/generated"

RUNTIME_INCLUDES = """\
#include <map>
#include <vector>
#include <cstring>
#include <cmath>
#include "runtime/dnnl_utils.h"
#include "runtime/blas_utils.h"
"""


def _extract_int_params(actor: IRActor) -> dict:
    """
    {param_name: int_value} from an actor's attached IRParams.
    Non-integer params (e.g. epsilon stored as "1en05") are silently skipped;
    their codegens read them directly from actor.attributes instead.
    """
    params = {}
    for _, param in actor.params:
        try:
            params[param.name] = int(param.value)
        except ValueError:
            pass
    return params


def generate_model_actors(graph: IRGraph, isHierarchial, model_name: str) -> dict[str, str]:
    """
    Generate one C++ function per unique operator type in the graph.

    Returns
    -------
    loop_fn_map : dict[actor.unique_name -> loop_fn_name]
        For generated actors: the base function name (e.g. "conv2d_bias").
        For non-generated actors: fallback from OPTYPE_TO_LOOP_FN.
    """
    os.makedirs(GENERATED_DIR, exist_ok=True)
    h_path   = os.path.join(GENERATED_DIR, f"{model_name}_actors.h")
    cpp_path = os.path.join(GENERATED_DIR, f"{model_name}_actors.cpp")

    declarations = []
    definitions  = []
    loop_fn_map  = {}
    seen_op_types: set[OpType] = set()

    for actor in graph.actors:
        codegen = get_codegen(actor.op_type)

        if codegen is None:
            # No generated kernel — keep the handwritten header/function.
            loop_fn_map[actor.unique_name] = OPTYPE_TO_LOOP_FN.get(actor.op_type, "")
            continue

        fn_name = codegen.loop_fn(actor)  # e.g. "conv2d_bias"
        loop_fn_map[actor.unique_name] = fn_name

        # An op is parallelized when hierarchical AND it gets a .pi subgraph
        is_parallel = (isHierarchial
                        and actor.op_type in OPTYPE_TO_PI
                        and actor.op_type not in SKIP_OPS)
        # Point the actor's graph_desc at the generated header so PREESM
        # finds the function declaration during code generation.
        if not is_parallel :
            actor.source = f"/Code/include/runtime/{model_name}_actors.h" 

        # Generate the function body only once per operator type.
        if actor.op_type not in seen_op_types:
            seen_op_types.add(actor.op_type)
            params = _extract_int_params(actor)
            declarations.append(codegen.decl(actor, params))
            definitions.append(codegen.defn(actor, params, parallel=is_parallel))

    # -----------------------------------------------------------------
    # Write header
    # -----------------------------------------------------------------
    with open(h_path, "w") as f:
        f.write("// Auto-generated by model_codegen.py — do not edit\n")
        f.write("#pragma once\n\n")
        f.write("\n".join(declarations))
        f.write("\n")

    # -----------------------------------------------------------------
    # Write implementation
    # -----------------------------------------------------------------
    with open(cpp_path, "w") as f:
        f.write("// Auto-generated by model_codegen.py — do not edit\n")
        f.write(RUNTIME_INCLUDES)
        f.write(f'#include "{model_name}_actors.h"\n')
        f.write("\n")
        f.write("\n\n".join(definitions))
        f.write("\n")

    print(f"  Generated {h_path}")
    print(f"  Generated {cpp_path}")
    return loop_fn_map
